name: agcm_environment
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - xesmf
  - matplotlib
  - netcdf4
  - pydap
  - dask
  - cartopy
  - pytorch
  - ipykernel
  - jupyter
  - pip:
      - torch-harmonics
